#!/usr/bin/env bash

RED='\033[0;31m'
LIGHTCYAN='\033[1;36m'
YELLOW='\033[1;33m'

if [ ! -f '.env' ]; then
    echo -e "${RED}.env dose not exists."
    echo -e "${LIGHTCYAN}Creating .env from .env.example"
    cp .env.example .env
fi

read -p $'\e[36mEnter your app port: ' appPort
appPort=${appPort:-8000}

read -p $'\e[36mEnter your db host port: ' forwardDbPort
forwardDbPort=${forwardDbPort:-5432}

if ! [[ "$appPort" =~ ^[+-]?[0-9]+\.?[0-9]*$ ]] || ! [[ "$forwardDbPort" =~ ^[+-]?[0-9]+\.?[0-9]*$ ]]
then
    echo -e "${RED}Port must be a numbers"
    exit 1
fi

echo -e "${LIGHTCYAN}Setting up"
sed -i '' -e "s|^APP_PORT=.*|APP_PORT=${appPort}|g" .env
sed -i '' -e "s|^FORWARD_DB_PORT=.*|FORWARD_DB_PORT=${forwardDbPort}|g" .env

echo -e "${LIGHTCYAN}Running ./vendor/bin/sail build --no-cache"
./vendor/bin/sail build --no-cache

echo -e "${LIGHTCYAN}Running ./vendor/bin/sail up -d\e[1;m"
./vendor/bin/sail up -d

echo -e "${LIGHTCYAN}Started with ${YELLOW}http://0.0.0.0:${appPort}"
